### ISSUE TITLE
Implement Fiduccia-Mattheyses algorithm

### ISSUE THREAD

**Issue by amanmehara** [CCNITSilchar/partitioning-algorithms#2]
Implement Fiduccia-Mattheyses algorithm in a programming language of your choice.

**Comment by sagarkar10** [comment]
Taking this one!

**Comment by amanmehara** [comment]
@sagarkar10 Waiting for the PR! 🎏

**Comment by sagarkar10** [comment]
@amanmehara Please review and Merge
